set_property PACKAGE_PIN N15 [get_ports clk_100MHz]
set_property IOSTANDARD LVCMOS33 [get_ports clk_100MHz]
create_clock -period 10.000 [get_ports clk_100MHz]

# start here
set_property -dict {PACKAGE_PIN J16 IOSTANDARD LVCMOS33} [get_ports vsync]
set_property -dict {PACKAGE_PIN J15 IOSTANDARD LVCMOS33} [get_ports pclk]
set_property -dict {PACKAGE_PIN K14 IOSTANDARD LVCMOS33} [get_ports hsync]


set_property -dict {PACKAGE_PIN G16 IOSTANDARD LVCMOS33} [get_ports {data[0]}]
set_property -dict {PACKAGE_PIN H18 IOSTANDARD LVCMOS33} [get_ports {data[1]}]
set_property -dict {PACKAGE_PIN E16 IOSTANDARD LVCMOS33} [get_ports {data[2]}]
set_property -dict {PACKAGE_PIN H16 IOSTANDARD LVCMOS33} [get_ports {data[3]}]
set_property -dict {PACKAGE_PIN C11 IOSTANDARD LVCMOS33} [get_ports {data[4]}]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD LVCMOS33} [get_ports {data[5]}]
set_property -dict {PACKAGE_PIN C12 IOSTANDARD LVCMOS33} [get_ports {data[6]}]
set_property -dict {PACKAGE_PIN H17 IOSTANDARD LVCMOS33} [get_ports {data[7]}]

set_property -dict {PACKAGE_PIN D11 IOSTANDARD LVCMOS33} [get_ports pwdn]
set_property -dict {PACKAGE_PIN D10 IOSTANDARD LVCMOS33} [get_ports reset]
set_property -dict {PACKAGE_PIN K16 IOSTANDARD LVCMOS33} [get_ports xclk]
# end here
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_grid[0]}]
set_property PACKAGE_PIN B3 [get_ports {hex_grid[3]}]
set_property PACKAGE_PIN C3 [get_ports {hex_grid[2]}]
set_property PACKAGE_PIN H6 [get_ports {hex_grid[1]}]
set_property PACKAGE_PIN G6 [get_ports {hex_grid[0]}]
set_property PACKAGE_PIN B5 [get_ports {hex_seg[7]}]
set_property PACKAGE_PIN C4 [get_ports {hex_seg[6]}]
set_property PACKAGE_PIN D6 [get_ports {hex_seg[5]}]
set_property PACKAGE_PIN D7 [get_ports {hex_seg[4]}]
set_property PACKAGE_PIN C5 [get_ports {hex_seg[3]}]
set_property PACKAGE_PIN D5 [get_ports {hex_seg[2]}]
set_property PACKAGE_PIN B4 [get_ports {hex_seg[1]}]
set_property PACKAGE_PIN E6 [get_ports {hex_seg[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {hex_seg[0]}]

set_property IOSTANDARD LVCMOS25 [get_ports btn_photo]
set_property PACKAGE_PIN J2 [get_ports btn_photo]